on:
  push:
    branches: [ release/* ]
  workflow_dispatch:

jobs:
  pre-release:
    uses: abbgrade/PsBuildTasks/.github/workflows/pre-release-windows.yml@c506ffc975dcb14c9fdd0579fe455054236ad7dc
    with:
      module-name: PsDataFactory
    secrets:
      ps-gallery-key: ${{ secrets.PS_GALLERY_KEY }}
